// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDlf_XQqqPka-7pHuiLx3Kszgl0gPlqE',
    appId: '1:994689580098:android:f6422fec6a92c259a181db',
    messagingSenderId: '994689580098',
    projectId: 'bankme-71af3',
    storageBucket: 'bankme-71af3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2LYsRVf9LSkYdZIP_kSJR05WEIVDbLzQ',
    appId: '1:994689580098:ios:ac7156c496b966aaa181db',
    messagingSenderId: '994689580098',
    projectId: 'bankme-71af3',
    storageBucket: 'bankme-71af3.appspot.com',
    iosClientId: '994689580098-2qmskkr3dj5k98022cq350csgvc2in4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2LYsRVf9LSkYdZIP_kSJR05WEIVDbLzQ',
    appId: '1:994689580098:ios:ac7156c496b966aaa181db',
    messagingSenderId: '994689580098',
    projectId: 'bankme-71af3',
    storageBucket: 'bankme-71af3.appspot.com',
    iosClientId: '994689580098-2qmskkr3dj5k98022cq350csgvc2in4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankMe',
  );
}
